/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PendaftaranMhs;

import PendaftaranMhs.LihatData;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.text.SimpleDateFormat;

/**
 *
 * @author USER
 */
public class DaftarMahasiswa extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;

    public DaftarMahasiswa() {
        initComponents();
        connect();
    }

    // Method to establish database connection
    public void connect() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/pendaftaranmhs", "root", "");
        } catch (ClassNotFoundException | SQLException ex) {
            ex.printStackTrace();
        }
    }

    public void loadData(String noPendaftaran, String nama, String programStudi, String jenisKelamin, String tempatLahir, String tanggalLahir, String agama, String alamat, String telepon, String email) {
        // Mengatur nilai dari masing-masing field form sesuai dengan data yang diterima
        txtNoPendaftaran.setText(noPendaftaran);
        txtNama.setText(nama);
        CmbBoxProgramStudi.setSelectedItem(programStudi);
        if (jenisKelamin.equals("Laki-Laki")) {
            BtnLakiLaki.setSelected(true);
        } else if (jenisKelamin.equals("Perempuan")) {
            BtnPerempuan.setSelected(true);
        }
        txtTempatLahir.setText(tempatLahir);
        txtTanggalLahir.setText(tanggalLahir); // Pastikan format tanggal sesuai
        txtAgama.setText(agama);
        txtAlamat.setText(alamat);
        txtTelepon.setText(telepon);
        txtEmail.setText(email);

        // Membuat field NoPendaftaran tidak dapat diedit karena biasanya merupakan key
        txtNoPendaftaran.setEditable(false);
    }

    // Event handlers for menu items
    // Event handlers for menu items
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelNoPendaftaran = new javax.swing.JLabel();
        labelProgramStudi = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        labelJenisKelamin = new javax.swing.JLabel();
        labelTempatLahir = new javax.swing.JLabel();
        labelTanggalLahir = new javax.swing.JLabel();
        labelAgama = new javax.swing.JLabel();
        labelAlamat = new javax.swing.JLabel();
        labelNoTelelpon = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        btnDaftarkan = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        txtNoPendaftaran = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtTempatLahir = new javax.swing.JTextField();
        txtTanggalLahir = new javax.swing.JTextField();
        txtAgama = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtTelepon = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        CmbBoxProgramStudi = new javax.swing.JComboBox<>();
        BtnLakiLaki = new javax.swing.JRadioButton();
        BtnPerempuan = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        txtMenuUtama = new javax.swing.JMenuItem();
        SeparatorMenuUtama = new javax.swing.JPopupMenu.Separator();
        txtEditData = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        txtManajemenMataKuliah = new javax.swing.JMenuItem();
        SeparatorEditData = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Form Pendaftaran");

        labelNoPendaftaran.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNoPendaftaran.setText("No. Pendaftaran");

        labelProgramStudi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelProgramStudi.setText("Program Studi Yang Dipilih");

        labelNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNama.setText("Nama ");

        labelJenisKelamin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelJenisKelamin.setText("Jenis Kelamin");

        labelTempatLahir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTempatLahir.setText("Tempat Lahir");

        labelTanggalLahir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTanggalLahir.setText("Tanggal Lahir YYYY-MM-DD");

        labelAgama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelAgama.setText("Agama");

        labelAlamat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelAlamat.setText("Alamat Lengkap ");

        labelNoTelelpon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNoTelelpon.setText("No. Telepon");

        labelEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelEmail.setText("Email ");

        btnDaftarkan.setText("Daftarkan ");
        btnDaftarkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarkanActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        CmbBoxProgramStudi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teknik Informatika - S1", "Sistem Informasi - S1", "Ilmu Komunikasi - S1", "Akutansi- S1", "Manajemen -S1", "Sastra Jepang - S1 " }));

        BtnLakiLaki.setText("Laki-Laki");

        BtnPerempuan.setText("Perempuan");

        jMenu1.setText("Daftar Mahasiswa");

        txtMenuUtama.setText("Menu Utama");
        txtMenuUtama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMenuUtamaActionPerformed(evt);
            }
        });
        jMenu1.add(txtMenuUtama);
        jMenu1.add(SeparatorMenuUtama);

        txtEditData.setText("Edit Data Mahasiswa");
        txtEditData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditDataActionPerformed(evt);
            }
        });
        jMenu1.add(txtEditData);
        jMenu1.add(jSeparator1);

        txtManajemenMataKuliah.setText("Manajemen Mata Kuliah");
        txtManajemenMataKuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManajemenMataKuliahActionPerformed(evt);
            }
        });
        jMenu1.add(txtManajemenMataKuliah);
        jMenu1.add(SeparatorEditData);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(btnDaftarkan)
                                .addGap(18, 18, 18)
                                .addComponent(btnReset))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelProgramStudi, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                    .addComponent(labelNoPendaftaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelNama, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelTempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelAgama, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelNoTelelpon, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelTanggalLahir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEmail)
                                    .addComponent(txtTelepon)
                                    .addComponent(txtAlamat)
                                    .addComponent(txtAgama)
                                    .addComponent(txtTanggalLahir)
                                    .addComponent(txtTempatLahir)
                                    .addComponent(txtNama)
                                    .addComponent(txtNoPendaftaran)
                                    .addComponent(CmbBoxProgramStudi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BtnLakiLaki, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnPerempuan, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNoPendaftaran, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoPendaftaran, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelProgramStudi, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(CmbBoxProgramStudi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNama, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnPerempuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelJenisKelamin, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(BtnLakiLaki, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAgama, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAgama, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNoTelelpon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnDaftarkan))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMenuUtamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMenuUtamaActionPerformed
        // TODO add your handling code here:
        new MenuUtama().setVisible(true);
    }//GEN-LAST:event_txtMenuUtamaActionPerformed

    private void txtEditDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditDataActionPerformed
        // TODO add your handing code here:
        new LihatData().setVisible(true);
    }//GEN-LAST:event_txtEditDataActionPerformed

    private void btnDaftarkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarkanActionPerformed
        // Kode dari registerStudent
        String noPendaftaran = txtNoPendaftaran.getText();
        String programStudi = CmbBoxProgramStudi.getSelectedItem().toString();
        String nama = txtNama.getText();
        String jenisKelamin = BtnLakiLaki.isSelected() ? "Laki-Laki" : "Perempuan";
        String tempatLahir = txtTempatLahir.getText();
        String tanggalLahir = txtTanggalLahir.getText();
        String agama = txtAgama.getText();
        String alamat = txtAlamat.getText();
        String telepon = txtTelepon.getText();
        String email = txtEmail.getText();

        try {
            pst = con.prepareStatement("INSERT INTO mahasiswa(noPendaftaran, programStudi, nama, jenisKelamin, tempatLahir, tanggalLahir, agama, alamat, telepon, email) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
            pst.setString(1, noPendaftaran);
            pst.setString(2, programStudi);
            pst.setString(3, nama);
            pst.setString(4, jenisKelamin);
            pst.setString(5, tempatLahir);
            pst.setString(6, tanggalLahir);
            pst.setString(7, agama);
            pst.setString(8, alamat);
            pst.setString(9, telepon);
            pst.setString(10, email);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Mahasiswa Berhasil Disimpan");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnDaftarkanActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // Kode dari resetForm
        txtNoPendaftaran.setText("");
        CmbBoxProgramStudi.setSelectedIndex(0);
        txtNama.setText("");
        BtnLakiLaki.setSelected(false);
        BtnPerempuan.setSelected(false);
        txtTempatLahir.setText("");
        txtTanggalLahir.setText("");
        txtAgama.setText("");
        txtAlamat.setText("");
        txtTelepon.setText("");
        txtEmail.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtManajemenMataKuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManajemenMataKuliahActionPerformed
        // TODO add your handling code here:
        new ManajemenMK().setVisible(true);
    }//GEN-LAST:event_txtManajemenMataKuliahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DaftarMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BtnLakiLaki;
    private javax.swing.JRadioButton BtnPerempuan;
    private javax.swing.JComboBox<String> CmbBoxProgramStudi;
    private javax.swing.JPopupMenu.Separator SeparatorEditData;
    private javax.swing.JPopupMenu.Separator SeparatorMenuUtama;
    private javax.swing.JButton btnDaftarkan;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel labelAgama;
    private javax.swing.JLabel labelAlamat;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelJenisKelamin;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelNoPendaftaran;
    private javax.swing.JLabel labelNoTelelpon;
    private javax.swing.JLabel labelProgramStudi;
    private javax.swing.JLabel labelTanggalLahir;
    private javax.swing.JLabel labelTempatLahir;
    private javax.swing.JTextField txtAgama;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JMenuItem txtEditData;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JMenuItem txtManajemenMataKuliah;
    private javax.swing.JMenuItem txtMenuUtama;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoPendaftaran;
    private javax.swing.JTextField txtTanggalLahir;
    private javax.swing.JTextField txtTelepon;
    private javax.swing.JTextField txtTempatLahir;
    // End of variables declaration//GEN-END:variables

    void SetVisible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
