/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PendaftaranMhs;

import javax.swing.*;
import java.awt.event.*;
import java.sql.*;
import java.util.ArrayList;

/**
 *
 * @author LENOVO
 */
public class InputKRS extends javax.swing.JFrame {

    /**
     * Creates new form InputKRS
     */
    public InputKRS() {
        initComponents();
        populateCourseCodes();
        populateStudentIDs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelInputKRS = new javax.swing.JLabel();
        jLabelMhs = new javax.swing.JLabel();
        jLabelMK = new javax.swing.JLabel();
        jComboBoxMhs = new javax.swing.JComboBox<>();
        jComboBoxMK = new javax.swing.JComboBox<>();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        txtMenuUtama = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        txtDaftarMahasiswa = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        txtLihatDataMahasiswa = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        txtManajemenMataKuliah = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelInputKRS.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelInputKRS.setText("INPUT KRS");

        jLabelMhs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelMhs.setText("Pilih Mahasiswa");

        jLabelMK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelMK.setText("Pilih Mata Kuliah");

        jComboBoxMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMhsActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        jMenu1.setText("Input KRS");

        txtMenuUtama.setText("Menu Utama");
        txtMenuUtama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMenuUtamaActionPerformed(evt);
            }
        });
        jMenu1.add(txtMenuUtama);
        jMenu1.add(jSeparator1);

        txtDaftarMahasiswa.setText("Daftar Mahasiswa");
        txtDaftarMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDaftarMahasiswaActionPerformed(evt);
            }
        });
        jMenu1.add(txtDaftarMahasiswa);
        jMenu1.add(jSeparator2);

        txtLihatDataMahasiswa.setText("Lihat Data Mahasiswa");
        txtLihatDataMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLihatDataMahasiswaActionPerformed(evt);
            }
        });
        jMenu1.add(txtLihatDataMahasiswa);
        jMenu1.add(jSeparator3);

        txtManajemenMataKuliah.setText("Manajemen Mata Kuliah");
        txtManajemenMataKuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManajemenMataKuliahActionPerformed(evt);
            }
        });
        jMenu1.add(txtManajemenMataKuliah);
        jMenu1.add(jSeparator4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBatal)
                        .addGap(146, 146, 146))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMhs)
                            .addComponent(jLabelMK))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelInputKRS)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jComboBoxMK, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxMhs, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabelInputKRS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMhs)
                    .addComponent(jComboBoxMhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMK)
                    .addComponent(jComboBoxMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnBatal))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMhsActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
       submitKRS();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalActionPerformed

    private void txtMenuUtamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMenuUtamaActionPerformed
        // TODO add your handling code here:
        new MenuUtama().setVisible(true);
    }//GEN-LAST:event_txtMenuUtamaActionPerformed

    private void txtDaftarMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDaftarMahasiswaActionPerformed
        // TODO add your handling code here:
        new DaftarMahasiswa().setVisible(true);
    }//GEN-LAST:event_txtDaftarMahasiswaActionPerformed

    private void txtLihatDataMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLihatDataMahasiswaActionPerformed
        // TODO add your handling code here:
        new LihatData().setVisible(true);
    }//GEN-LAST:event_txtLihatDataMahasiswaActionPerformed

    private void txtManajemenMataKuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManajemenMataKuliahActionPerformed
        // TODO add your handling code here:
        new ManajemenMK().setVisible(true);
    }//GEN-LAST:event_txtManajemenMataKuliahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputKRS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputKRS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputKRS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputKRS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputKRS().setVisible(true);
            }
        });
    }

         private void populateCourseCodes() {
        Connection conn = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;
        
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pendaftaranmhs", "root", "");
            String sql = "SELECT id_mk, nama_mk FROM matakuliah";
            pstmt = conn.prepareStatement(sql);
            rs = pstmt.executeQuery();

            while (rs.next()) {
                String courseInfo = rs.getString("id_mk") + " - " + rs.getString("nama_mk");
                jComboBoxMK.addItem(courseInfo);
            }
        } catch (SQLException se) {
            se.printStackTrace();
        } finally {
            try {
                if (rs != null) rs.close();
                if (pstmt != null) pstmt.close();
                if (conn != null) conn.close();
            } catch (SQLException se) {
                se.printStackTrace();
            }
        }
    }

    private void populateStudentIDs() {
        Connection conn = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;

        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pendaftaranmhs", "root", "");
            String sql = "SELECT noPendaftaran FROM mahasiswa";
            pstmt = conn.prepareStatement(sql);
            rs = pstmt.executeQuery();

            while (rs.next()) {
                jComboBoxMhs.addItem(String.valueOf(rs.getInt("noPendaftaran")));
            }
        } catch (SQLException se) {
            se.printStackTrace();
        } finally {
            try {
                if (rs != null) rs.close();
                if (pstmt != null) pstmt.close();
                if (conn != null) conn.close();
            } catch (SQLException se) {
                se.printStackTrace();
            }
        }
    }
    private void submitKRS() {
    String selectedCourseInfo = (String) jComboBoxMK.getSelectedItem();
    String[] parts = selectedCourseInfo.split(" - ");
    int selectedCourseID = Integer.parseInt(parts[0].trim());

    int selectedStudentID = Integer.parseInt((String) jComboBoxMhs.getSelectedItem());

    Connection conn = null;
    PreparedStatement pstmt = null;
    PreparedStatement pstmtUpdateSKS = null;
    ResultSet rs = null;

    try {
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/pendaftaranmhs", "root", "");

        // Insert into registrasi table
        String sql = "INSERT INTO registrasi (id_mk, noPendaftaran) VALUES (?, ?)";
        pstmt = conn.prepareStatement(sql);
        pstmt.setInt(1, selectedCourseID);
        pstmt.setInt(2, selectedStudentID);

        int affectedRows = pstmt.executeUpdate();

        if (affectedRows > 0) {
            // Get the SKS of the selected course
            String sqlGetSKS = "SELECT sks FROM matakuliah WHERE id_mk = ?";
            pstmtUpdateSKS = conn.prepareStatement(sqlGetSKS);
            pstmtUpdateSKS.setInt(1, selectedCourseID);
            rs = pstmtUpdateSKS.executeQuery();

            int sks = 0;
            if (rs.next()) {
                sks = rs.getInt("sks");
            }

            // Update the total SKS in mahasiswa table
            String sqlUpdateSKS = "UPDATE mahasiswa SET total_sks = total_sks + ? WHERE noPendaftaran = ?";
            pstmtUpdateSKS = conn.prepareStatement(sqlUpdateSKS);
            pstmtUpdateSKS.setInt(1, sks);
            pstmtUpdateSKS.setInt(2, selectedStudentID);

            int rowsUpdated = pstmtUpdateSKS.executeUpdate();

            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(this, "KRS successfully submitted and SKS updated.");
            } else {
                JOptionPane.showMessageDialog(this, "KRS submitted, but failed to update SKS.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error submitting KRS.");
        }
    } catch (SQLException se) {
        se.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error submitting KRS. " + se.getMessage());
    } finally {
        try {
            if (rs != null) rs.close();
            if (pstmt != null) pstmt.close();
            if (pstmtUpdateSKS != null) pstmtUpdateSKS.close();
            if (conn != null) conn.close();
        } catch (SQLException se) {
            se.printStackTrace();
        }
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> jComboBoxMK;
    private javax.swing.JComboBox<String> jComboBoxMhs;
    private javax.swing.JLabel jLabelInputKRS;
    private javax.swing.JLabel jLabelMK;
    private javax.swing.JLabel jLabelMhs;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenuItem txtDaftarMahasiswa;
    private javax.swing.JMenuItem txtLihatDataMahasiswa;
    private javax.swing.JMenuItem txtManajemenMataKuliah;
    private javax.swing.JMenuItem txtMenuUtama;
    // End of variables declaration//GEN-END:variables
}